"""
Django settings for businesswebsite project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
import django
from datetime import date
import dj_database_url

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'django.friendly_captcha': {
    'handlers': ['default'],
    'level': 'INFO',
    }
}

USE_CART = False 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-ALLOWED_HOSTSc 
# something like .example.com will match both www and non www
ALLOWED_HOSTS = [".overlandelectricians.com", '.herokuapp.com']

# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic', #disables django.contrib.staticfiles, allows whitenoise to take over serving static files
    'django.contrib.admin',#'businesswebsite.apps.MyAdminConfig', # replaces 'django.contrib.admin'
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',
    'django.contrib.sitemaps',
    'mainsite',
    'schedule',
]

# CSRF_TRUSTED_ORIGINS = ["https://*.ngrok.io", ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # must be placed directly after django.middleware.security.SecurityMiddleware and before everything else
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'businesswebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),'mainsite/templates/mainsite/', django.__path__[0] + '/forms/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

WSGI_APPLICATION = 'businesswebsite.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Denver'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# Static files per app
STATIC_URL = 'static/'

# Other places to look for static files 
# not tied to any particular app

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

COMPANY_NAME = 'Rocky Mountain Overland Electrians'

# Sitemap settings
SITEMAP_DEFAULT_LAST_MOD = date.year

WHITENOISE_USE_FINDERS = True # allows serving files directly from their original location without having to call collectstatic to collect into STATIC_ROOT
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' # File compression and unique naming per version so they can be cached forever

# ENVIRONMENT VARIABLES BELOW HERE #

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
else:
    DATABASES = {
        'development': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': "maindb",
            'USER': "postgres",
            'PASSWORD': os.environ.get('DB_PASS'),
            'HOST': "localhost",
            'PORT': 5432,
        }
    }

# Email settings 
DEFAULT_FROM_EMAIL = 'admin@overlandelectrians.com'
SERVER_EMAIL = 'admin@overlandelectrians.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_PORT = os.environ.get('EMAIL_HOST_PORT') 

# SECURITY WARNING: keep the secret key used in production secret!
# TODO: move this to the keyring before going live on production
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# Friendly CAPTCHA settings
# The API key
FRC_CAPTCHA_SECRET = os.environ.get('FRC_CAPTCHA_SECRET')
FRC_CAPTCHA_SITE_KEY = os.environ.get('FRC_CAPTCHA_SITE_KEY')
FRC_CAPTCHA_VERIFICATION_URL = 'https://api.friendlycaptcha.com/api/v1/siteverify'
# Fail silent set to True means you have to handle what to do with verification in the forms view
# Setting False will just cause the form to fail with an error ('Captcha test failed')
FRC_CAPTCHA_FAIL_SILENT = False


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Debug settings
if (DEBUG):
    ALLOWED_HOSTS += 'localhost'
    ALLOWED_HOSTS += '*.ngrok.io'
else:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
