# Generated by Django 4.0.4 on 2022-09-26 00:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A title in question format. Full length. 50 characters.', max_length=50)),
                ('entry', models.TextField(help_text='A markdown embellished entry for the this FAQ question. 5000 characters.', max_length=5000)),
                ('pub_date', models.DateField(default=django.utils.timezone.localdate)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='slooog', help_text='A unique slug used in the url.', max_length=255, unique=True)),
                ('short_title', models.CharField(help_text='A short title for display on small devices. 50 characters.', max_length=50)),
                ('medium_title', models.CharField(help_text='A medium length title for display on medium devices. 100 characters.', max_length=100)),
                ('short_description', models.TextField(default='Knowledge base entry short description', help_text='A short description for display on small devices. 500 characters.', max_length=500)),
                ('entry', models.TextField(default='Knowledge base entry', help_text='A markdown embellished entry for the this knowledge base topic. 10000 characters. About 2000 words.', max_length=10000)),
                ('author', models.CharField(default='Uknown Author', help_text='The author of this article.', max_length=40)),
                ('draft', models.BooleanField(default=True, help_text="Set to true when the article is being drafted, set to false when you want to be published. This feature is only used by the sitemap builder to ensure articles under construction aren't listed as crawlable by robots.")),
                ('category', models.ForeignKey(blank=True, help_text='ID of the appropriate category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.knowledgebasecategory')),
            ],
        ),
    ]
